GrottaFrancigena_2F_MapScripts::
	.byte 0


GrottaFrancigena_2F_Roberta::
# 6 "data//layouts/GrottaFrancigena_2F/scripts.pory"
	msgbox GrottaFrancigena_2F_Roberta_Text_0, MSGBOX_NPC
# 7 "data//layouts/GrottaFrancigena_2F/scripts.pory"
	closemessage
	return


GrottaFrancigena_2F_Luca::
# 12 "data//layouts/GrottaFrancigena_2F/scripts.pory"
	msgbox GrottaFrancigena_2F_Luca_Text_0, MSGBOX_NPC
# 13 "data//layouts/GrottaFrancigena_2F/scripts.pory"
	closemessage
	return


GrottaFrancigena_2F_Roberta_Text_0:
# 6 "data//layouts/GrottaFrancigena_2F/scripts.pory"
	.string "ROBERTA: Ciao Ali, ho portato luca qui\n"
	.string "per infrattarci, ma chiss n gl n te'$"

GrottaFrancigena_2F_Luca_Text_0:
# 12 "data//layouts/GrottaFrancigena_2F/scripts.pory"
	.string "LUCA:n mn te'$"
