gText_Birch_Welcome::
	.string "Ben arr'uata p'ddentr agl munn \n"
	.string "di'j Pokemonn'!\p"
	.string "I so BIRCH.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "i st cos e' “POKéMONN'.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "St munn e' r'kin d ss criatur.\p" 
	.string "\n"
	.string "$"

gText_Birch_AndYouAre::
	.string "M fa piacer d'incuntrart ALICE\p"
	.string "\n"
	.string "$"  

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string " {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Adde' fa' I cos in grand.\p"
	.string "M raccumman Signori' MELE!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Uan i kiappagn tutt.!\p"
	.string "\n"
	.string "$"  
