gText_Birch_Welcome::
	.string "Benvenuti nel mondo dei POKéMON!\p"
	.string "Io sono BIRCH.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "E questo qui e' un “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Questo e' un mondo popolato\n"
	.string "da creature chiamate POKéMON.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "E' un piacere conoscerti ALICE$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string " {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Benvenuta in questo mondo!\p"
	.string "Fai come se fossi a casa tua!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "E ricorda\p"
	.string "Acchiappali tutti!\n"
	.string "$"
