gText_ObtainedTheItem::
	.string "Obtained the {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "The BAG is full…$"

gText_PutItemInPocket::
	.string "{PLAYER} ha messo {STR_VAR_2}\n"
	.string "nella {STR_VAR_3} tasca.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} ha trovato {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Mannaggia!\n"
	.string "La borsa e' piena…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} ha messo {STR_VAR_2}\n"
	.string "nello zaino.$"

gText_ObtainedTheDecor::
	.string "Obtained the {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"

gText_ObtainedTheItems::
	.string "Ha ottenuto {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "{PLAYER} ha trovato {STR_VAR_1} {STR_VAR_2}!$"
